### ISSUE TITLE
iOS 7 TextView is shrunken

### ISSUE THREAD

**Issue by segiddins** [brandonhamilton/inputtoolbar#20] opened 2013-07-26 16:15 UTC
![ios simulator screen shot jul 26 2013 12 15 18 pm](https://f.cloud.github.com/assets/1946610/863647/9d58e77a-f60e-11e2-82b4-080e0245d29d.png)

**Comment by brandonhamilton** [comment] 2013-07-29 08:32
The issue seems to be with the height calculation in UIExpandingTextView (setMaximumNumberOfLines, setMinimumNumberOfLines), where the following does not seem to return the correct height of multi-line text:

```
textHeight = self.internalTextView.contentSize.height;
```

It seems that getting the actual height of multi-line text should be done as follows:

```
CGSize boundingSize = CGSizeMake(self.internalTextView.frame.size.width, CGFLOAT_MAX);
CGSize textSize = [multiLineTextString sizeWithFont:self.internalTextView.font
                             constrainedToSize:boundingSize 
                                 lineBreakMode:UILineBreakModeWordWrap];
textHeight = textSize.height;
```

**Comment by segiddins** [comment] 2013-07-29 14:13
Hmm… I'll have to check that out

**Comment by rsoffer** [comment] 2013-09-06 15:11
Any update on this?  Killing me on iOS 7 transitioning.

**Comment by zzz6519003** [comment] 2013-09-20 14:20
@rsoffer me, too... set this as a milestone!

**Comment by segiddins** [comment] 2013-10-12 23:42
@brandonhamilton Your fix doesn't work

**Comment by sanjerali** [comment] 2013-10-14 15:08
The content size property no longer works as it did on iOS 6. Using sizeToFit as others suggest may or may not work depending on a number of factors. Thanks to Tarmes on http://stackoverflow.com/questions/19046969/uitextview-content-size-different-in-ios7 for a function to calculate the height for a textview on iOS7 made this beutiful inputToolbar ready for iOS7. Thanks BrandonHamilton and Tarmes.

Here is the solution.

Add the below function to UIExpandingTextView.m

/*************************************************************************************************_/
/_ function to measure the textView Height in ios7 */
- (CGFloat)measureHeightOfUITextView:(UITextView *)textView
  {
  if ([textView respondsToSelector:@selector(snapshotViewAfterScreenUpdates:)])
  {
      // This is the code for iOS 7. contentSize no longer returns the correct value, so
      // we have to calculate it.
      //
      // This is partly borrowed from HPGrowingTextView, but I've replaced the
      // magic fudge factors with the calculated values (having worked out where
      // they came from)
  
  ```
  CGRect frame = textView.bounds;
  
  // Take account of the padding added around the text.
  
  UIEdgeInsets textContainerInsets = textView.textContainerInset;
  UIEdgeInsets contentInsets = textView.contentInset;
  
  CGFloat leftRightPadding = textContainerInsets.left + textContainerInsets.right + textView.textContainer.lineFragmentPadding * 2 + contentInsets.left + contentInsets.right;
  CGFloat topBottomPadding = textContainerInsets.top + textContainerInsets.bottom + contentInsets.top + contentInsets.bottom;
  
  frame.size.width -= leftRightPadding;
  frame.size.height -= topBottomPadding;
  
  NSString *textToMeasure = textView.text;
  if ([textToMeasure hasSuffix:@"\n"])
  {
      textToMeasure = [NSString stringWithFormat:@"%@-", textView.text];
  }
  
  // NSString class method: boundingRectWithSize:options:attributes:context is
  // available only on ios7.0 sdk.
  
  NSMutableParagraphStyle *paragraphStyle = [[NSMutableParagraphStyle alloc] init];
  [paragraphStyle setLineBreakMode:NSLineBreakByWordWrapping];
  
  NSDictionary *attributes = @{ NSFontAttributeName: textView.font, NSParagraphStyleAttributeName : paragraphStyle };
  
  CGRect size = [textToMeasure boundingRectWithSize:CGSizeMake(CGRectGetWidth(frame), MAXFLOAT)
                                            options:NSStringDrawingUsesLineFragmentOrigin
                                         attributes:attributes
                                            context:nil];
  
  CGFloat measuredHeight = ceilf(CGRectGetHeight(size) + topBottomPadding);
  return measuredHeight+8.0f;
  ```
  
  }
  else
  {
      return textView.contentSize.height;
  }
  }

/**************************************************************************************************/

And in the same file replace the following functions with the functions updated to call the above function.

-(void)setMaximumNumberOfLines:(int)n
{
    BOOL didChange            = NO;
    NSString *saveText        = self.internalTextView.text;
    NSString *newText         = @"-";
    self.internalTextView.hidden   = YES;
    self.internalTextView.delegate = nil;
    for (int i = 2; i < n; ++i)
    {
        newText = [newText stringByAppendingString:@"\n|W|"];
    }
    self.internalTextView.text     = newText;

```
/*fix for iOS7 */
if(floor(NSFoundationVersionNumber)>NSFoundationVersionNumber_iOS_6_1) {
    didChange = (self.maximumHeight != [self measureHeightOfUITextView:self.internalTextView]);
}
else {
    didChange = (self.maximumHeight != self.internalTextView.contentSize.height);
}
if(floor(NSFoundationVersionNumber)>NSFoundationVersionNumber_iOS_6_1) {
    self.maximumHeight             = [self measureHeightOfUITextView:self.internalTextView];
} else {
    self.maximumHeight             = self.internalTextView.contentSize.height;
}
```

//    self.maximumHeight             = self.internalTextView.contentSize.height;
    _maximumNumberOfLines      = n;
    self.internalTextView.text     = saveText;
    self.internalTextView.hidden   = NO;
    self.internalTextView.delegate = self;
    if (didChange) {
        self.forceSizeUpdate = YES;
        [self textViewDidChange:self.internalTextView];
    }
}

-(void)setMinimumNumberOfLines:(int)m
{
    NSString _saveText        = self.internalTextView.text;
    NSString *newText         = @"-";
    self.internalTextView.hidden   = YES;
    self.internalTextView.delegate = nil;
    for (int i = 2; i < m; ++i)
    {
        newText = [newText stringByAppendingString:@"\n|W|"];
    }
    self.internalTextView.text     = newText;
    /_ below line is fix */
    if(floor(NSFoundationVersionNumber) > NSFoundationVersionNumber_iOS_6_1) {
        self.minimumHeight             = [self measureHeightOfUITextView:self.internalTextView];
    }
    else {
            self.minimumHeight             = self.internalTextView.contentSize.height;
    }

```
self.internalTextView.text     = saveText;
self.internalTextView.hidden   = NO;
self.internalTextView.delegate = self;
[self sizeToFit];
_minimumNumberOfLines = m;
```

}
- (void)textViewDidChange:(UITextView *)textView
  {
  if(textView.text.length == 0)
      self.placeholderLabel.alpha = 1;
  else
      self.placeholderLabel.alpha = 0;
  
  NSInteger newHeight;
  if(floor(NSFoundationVersionNumber)>NSFoundationVersionNumber_iOS_6_1) {
  
  ```
  newHeight = [self measureHeightOfUITextView:self.internalTextView];
  ```
  
  }else {
      newHeight = self.internalTextView.contentSize.height;
  }
  
  //NSInteger newHeight = self.internalTextView.contentSize.height;
  
  if(newHeight < self.minimumHeight || !self.internalTextView.hasText)
  {
      newHeight = self.minimumHeight;
  }
  
  if (self.internalTextView.frame.size.height != newHeight || self.forceSizeUpdate)
  {
      self.forceSizeUpdate = NO;
      if (newHeight > self.maximumHeight && self.internalTextView.frame.size.height <= self.maximumHeight)
      {
          newHeight = self.maximumHeight;
      }
      if (newHeight <= self.maximumHeight)
      {
          if(self.animateHeightChange)
          {
              [UIView beginAnimations:@"" context:nil];
              [UIView setAnimationDelegate:self];
              [UIView setAnimationDidStopSelector:@selector(growDidStop)];
              [UIView setAnimationBeginsFromCurrentState:YES];
          }
  
  ```
      if ([self.delegate respondsToSelector:@selector(expandingTextView:willChangeHeight:)])
      {
          [self.delegate expandingTextView:self willChangeHeight:(newHeight+ kTextInsetBottom)];
      }
  
      /* Resize the frame */
      CGRect r = self.frame;
      r.size.height = newHeight + kTextInsetBottom;
      self.frame = r;
      r.origin.y = 0;
      r.origin.x = 0;
      self.internalTextView.frame = CGRectInset(r, kTextInsetX, 0);
      r.size.height -= 8;
      self.textViewBackgroundImage.frame = r;
  
      if(self.animateHeightChange)
      {
          [UIView commitAnimations];
      }
      else if ([self.delegate respondsToSelector:@selector(expandingTextView:didChangeHeight:)])
      {
          [self.delegate expandingTextView:self didChangeHeight:(newHeight+ kTextInsetBottom)];
      }
  }
  
  if (newHeight >= self.maximumHeight)
  {
      /* Enable vertical scrolling */
      if(!self.internalTextView.scrollEnabled)
      {
          self.internalTextView.scrollEnabled = YES;
          [self.internalTextView flashScrollIndicators];
      }
  }
  else
  {
      /* Disable vertical scrolling */
      self.internalTextView.scrollEnabled = NO;
  }
  ```
  
  }
  
  if ([self.delegate respondsToSelector:@selector(expandingTextViewDidChange:)])
  {
      [self.delegate expandingTextViewDidChange:self];
  }

}

Hope that helps us all.

**Comment by segiddins** [comment] 2013-10-14 21:49
@sanjerali could you make a branch and submit a PR for us to review?

**Comment by brandonhamilton** [comment] 2013-10-15 09:23
I have merged in the code from @sanjerali above (see c50350943fe6727a6c81a22601285c715c1936b4).

**Comment by sanjerali** [comment] 2013-10-15 09:28
Thanks Brandon. If i am correct, you may need to edit your above comment to " it NOW works for ios7"?

**Comment by brandonhamilton** [comment] 2013-10-15 09:38
@sanjerali Thanks for the work on this problem - it does seem that your solution works.

That previous comment was just closing of another issue (#24) that has been marked at a duplicate of the current one, not a comment on the status of this issue.

**Comment by zhangzhixun** [comment] 2014-02-14 01:50
It works! Thanks for your @sanjerali help!

**Closed as completed** 2014-02-14 08:52 UTC
